language: node_js:
addons:
  sonarcloud:
    organization: "jakubmroczek"
    token:
      secure: $SONAR_TOKEN
node_js:
  - "12.10"
before_install:
  - cd ./api
  - npm install
  - npm test
  - npm run build
  - cd ./ui
  - npm install
  - npm test
  - npm run build
on:
  branch: master
